esphome:
  name: wellmon
  friendly_name: wellmon

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# # Enable Home Assistant API
# api:
#   encryption:
#     key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# ota:
#   - platform: esphome
#     password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

sensor:
  - platform: adc
    pin: GPIO36
    name: "Water Pressure Sensor"
    attenuation: 12db
    update_interval: 0.5s
    unit_of_measurement: PSI
    filters:
      - median:
          window_size: 10
          send_every: 10
          send_first_at: 1
      # - lambda: 'ESP_LOGD("adc", "Raw ADC Value: %f", x); return x;'
      - calibrate_linear:
        - 0.34 -> 0
        - 0.61 -> 10
        - 0.90 -> 20
        - 1.14 -> 30
        - 1.43 -> 40
        - 1.69 -> 50
        - 1.95 -> 60
        - 2.22 -> 70
        - 2.42 -> 80
        - 2.67 -> 90
        - 2.90 -> 100
